name = "cf-workers-chatgpt-discord-bot"
main = "src/index.ts"
compatibility_date = "2023-03-02"
workers_dev = true

kv_namespaces = [
    { binding = "CHATGPT_DISCORD_BOT_KV", id = "33465fe6ac95461fbaf44b50490a4bfd" }
]

[vars]
DISCORD_USERID_WHITELIST = "115383559790919689 360096828609396737" # jaryl, jonsee
CHATGPT_MODEL = "gpt-3.5-turbo"
CONTEXT = 1
